#!/bin/sh

# This file runs when a DM logs you into a graphical session.  If you use startx/xinit like a Chad, this file will also be sourced.
# Fix Gnome Apps Slow  Start due to failing services
#Add this when you include flatpak in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

. $HOME/.config/xprofile.local
xset r rate 300 50 &	# Speed xrate up
xrdb ~/.config/Xresources 	# Uncomment to use Xresources colors/settings on startup
xrdb -merge ~/.config/Xresources.local 	# Include local file

$COMP &
$PLASMA &
$STATUSBAR &
$CLUTTER &
$SHORTCUTS &



# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
"

# EXAMPLES FOR ~/.config/xprofile.local
# # no export needed
# PLASMA="kstart5 plasmashell"
# COMP=compton
# CLUTTER=unclutter
# SHORTCUTS="launch_sxhkd && remaps &"

# # export because used by shortcuts
# export TERMINAL=st
# export BROWSER=chromium-browser
# export SEARCHBAR="kstart5 krunner"
# export STATUSBAR="latte-dock" 
