-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- require("plugins.nonlazy.dap").setup()
-- require("plugins.nonlazy.diagnostic").setup()
-- require("plugins.nonlazy.lualine").setup()
-- require("plugins.nonlazy.nvim-window").setup()
-- require("plugins.nonlazy.refactoring").setup()

-- require("plugins.nonlazy.leap").setup()
-- require("plugins.nonlazy.lsp-format").setup()
-- require("plugins.nonlazy.lsp").setup()
-- require("plugins.nonlazy.luasnip").setup()
-- require("plugins.nonlazy.neodev").setup()
-- require("plugins.nonlazy.null-ls").setup()
-- require("plugins.nonlazy.nvim-cmp").setup()
-- require("plugins.nonlazy.nvim-lsp-ts-utils").setup()
-- require("plugins.nonlazy.nvim-treesitter").setup()
-- require("plugins.nonlazy.nvim-treesitter-textobjects").setup()
-- require("plugins.nonlazy.telescope").setup()
-- require("plugins.nonlazy.trouble").setup()
